[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#F8F8F2"

[icons ]
icons = "awesome4"
[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = ["|^|"]
bat_not_available = "|?|"

[[block]]
block = "sound"
step_width = 3
format = "$icon"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 1
format = "$icon $frequency $utilization $boost"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon RTX 4080 ($clocks $utilization $temperature)"

[[block]]
block = "memory"
interval = 1
format = " $icon $mem_total($mem_used+$mem_avail)"
format_alt = "$icon_swap $swap_used"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $total ($used+$available)"

[[block]]
block = "battery"
driver = "upower"
format = " $icon $percentage "

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:' %a, %b %d %Y %R')"
