[theme]
name = "modern"

[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#F8F8F2"

[icons ]
name = "awesome"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {frequency}GHz {utilization}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}"
format_swap = "{swap_used;G}"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%R %a, %b %d %Y"
