[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#F8F8F2"

[icons ]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 1
format = "$icon $barchart $frequency $boost $utilization"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon$mem_used/$mem_free"
format_alt = "$icon_swap $swap_used"

[[block]]
block = "battery"
driver = "upower"
format = "$percentage"

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:' %a, %b %d %Y %R')"
